version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: avito_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: charaf
      POSTGRES_DB: avito_dw
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pipeline:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: avito_pipeline
    depends_on:
      - postgres
    env_file:
      - ../.env
    volumes:
      - ..:/app
      - ../staging:/app/staging
      - ../logs:/app/logs

volumes:
  pg_data: